### ISSUE TITLE
README: privacy

### ISSUE THREAD

**Issue by huyz** [inlife/spx#3]
Could you add privacy implications to the README? thanks

**Comment by inlife** [comment]
Hey @huyz 

Could you elaborate on that? I think it is possible, I'm just not entirely sure what you would like to see there.

Thanks!

**Comment by huyz** [comment]
- Does your site log URLs upon creation?
- Does your site log URLs upon click?

Are these above questions even technically relevant?

**Comment by inlife** [comment]
Added the information: https://github.com/inlife/spx#privacy
